# Generated by Django 4.1 on 2022-10-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imageuploader_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuploader',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/'),
        ),
    ]
